- name: Gather EC2 Facts
  action: ec2_facts

- name: Lay down Rancher Server init script via Template
  template:
    src: rancher-server-init.sh.j2
    dest: /usr/local/lib/rancher-server-init.sh
    owner: root
    mode: 0755
